/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica se a API está no ar */
        get: operations["AppController_verificarSaude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria uma conta com papel USUARIO e devolve o token */
        post: operations["AutenticacaoController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica com email e senha e devolve o token */
        post: operations["AutenticacaoController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados do usuário autenticado */
        get: operations["UsuariosController_buscarAtual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuários, com filtro por papel e busca por nome/email (ADMIN) */
        get: operations["UsuariosController_listar"];
        put?: never;
        /** Cria um usuário com qualquer papel (ADMIN) */
        post: operations["UsuariosController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui um usuário sem chamados nem comentários (ADMIN) */
        delete: operations["UsuariosController_excluir"];
        options?: never;
        head?: never;
        /** Altera nome, email, papel ou senha de um usuário (ADMIN) */
        patch: operations["UsuariosController_atualizar"];
        trace?: never;
    };
    "/api/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as categorias em ordem alfabética */
        get: operations["CategoriasController_listar"];
        put?: never;
        /** Cria uma categoria (ADMIN) */
        post: operations["CategoriasController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui uma categoria; os chamados dela ficam sem categoria (ADMIN) */
        delete: operations["CategoriasController_excluir"];
        options?: never;
        head?: never;
        /** Renomeia uma categoria (ADMIN) */
        patch: operations["CategoriasController_atualizar"];
        trace?: never;
    };
    "/api/chamados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista chamados com filtros; USUARIO vê só os próprios */
        get: operations["ChamadosController_listar"];
        put?: never;
        /** Abre um chamado em nome do usuário autenticado */
        post: operations["ChamadosController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chamados/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do chamado com comentários */
        get: operations["ChamadosController_buscarPorId"];
        put?: never;
        post?: never;
        /** Exclui o chamado (ADMIN, ou o solicitante enquanto aberto) */
        delete: operations["ChamadosController_excluir"];
        options?: never;
        head?: never;
        /** Edita título, descrição, prioridade ou categoria (solicitante só enquanto aberto) */
        patch: operations["ChamadosController_atualizar"];
        trace?: never;
    };
    "/api/chamados/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera o status (AGENTE/ADMIN) */
        patch: operations["ChamadosController_atualizarStatus"];
        trace?: never;
    };
    "/api/chamados/{id}/responsavel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Define o responsável (AGENTE só assume para si; ADMIN atribui a qualquer atendente) */
        patch: operations["ChamadosController_atualizarResponsavel"];
        trace?: never;
    };
    "/api/chamados/{id}/comentarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adiciona um comentário e devolve o chamado atualizado */
        post: operations["ChamadosController_adicionarComentario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegistrarDto: {
            nome: string;
            email: string;
            senha: string;
        };
        /** @enum {string} */
        Papel: "USUARIO" | "AGENTE" | "ADMIN";
        UsuarioDto: {
            id: number;
            nome: string;
            email: string;
            papel: components["schemas"]["Papel"];
        };
        AuthRespostaDto: {
            token: string;
            usuario: components["schemas"]["UsuarioDto"];
        };
        LoginDto: {
            /** @example admin@local.dev */
            email: string;
            senha: string;
        };
        CriarUsuarioDto: {
            nome: string;
            email: string;
            senha: string;
            papel: components["schemas"]["Papel"];
        };
        AtualizarUsuarioDto: {
            nome?: string;
            email?: string;
            senha?: string;
            papel?: components["schemas"]["Papel"];
        };
        CategoriaDto: {
            id: number;
            nome: string;
        };
        SalvarCategoriaDto: {
            nome: string;
        };
        /** @enum {string} */
        PrioridadeChamado: "BAIXA" | "MEDIA" | "ALTA";
        CriarChamadoDto: {
            titulo: string;
            descricao: string;
            prioridade?: components["schemas"]["PrioridadeChamado"];
            categoriaId?: number;
        };
        /** @enum {string} */
        StatusChamado: "ABERTO" | "EM_ANDAMENTO" | "RESOLVIDO" | "FECHADO";
        UsuarioResumoDto: {
            id: number;
            nome: string;
            email: string;
        };
        ComentarioDto: {
            id: number;
            mensagem: string;
            /** Format: date-time */
            criadoEm: string;
            autor: components["schemas"]["UsuarioResumoDto"];
        };
        ChamadoDto: {
            id: number;
            titulo: string;
            descricao: string;
            status: components["schemas"]["StatusChamado"];
            prioridade: components["schemas"]["PrioridadeChamado"];
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            atualizadoEm: string;
            categoria: components["schemas"]["CategoriaDto"] | null;
            solicitante: components["schemas"]["UsuarioResumoDto"];
            responsavel: components["schemas"]["UsuarioResumoDto"] | null;
            comentarios?: components["schemas"]["ComentarioDto"][];
        };
        /** @enum {string} */
        FiltroAtribuicao: "MEUS" | "SEM_RESPONSAVEL";
        AtualizarChamadoDto: {
            titulo?: string;
            descricao?: string;
            prioridade?: components["schemas"]["PrioridadeChamado"];
            /** @description null remove a categoria */
            categoriaId?: number | null;
        };
        AtualizarStatusDto: {
            status: components["schemas"]["StatusChamado"];
        };
        AtualizarResponsavelDto: {
            responsavelId: number;
        };
        CriarComentarioDto: {
            mensagem: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_verificarSaude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AutenticacaoController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRespostaDto"];
                };
            };
        };
    };
    AutenticacaoController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRespostaDto"];
                };
            };
        };
    };
    UsuariosController_buscarAtual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    UsuariosController_listar: {
        parameters: {
            query?: {
                papel?: components["schemas"]["Papel"];
                /** @description Texto buscado no nome ou no email */
                busca?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"][];
                };
            };
        };
    };
    UsuariosController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarUsuarioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    UsuariosController_excluir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsuariosController_atualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarUsuarioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    CategoriasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
        };
    };
    CategoriasController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalvarCategoriaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
        };
    };
    CategoriasController_excluir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriasController_atualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalvarCategoriaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
        };
    };
    ChamadosController_listar: {
        parameters: {
            query?: {
                status?: components["schemas"]["StatusChamado"];
                prioridade?: components["schemas"]["PrioridadeChamado"];
                categoriaId?: number;
                /** @description Texto buscado no título ou na descrição */
                busca?: string;
                /** @description MEUS = sou o responsável; SEM_RESPONSAVEL = ninguém assumiu */
                atribuicao?: components["schemas"]["FiltroAtribuicao"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"][];
                };
            };
        };
    };
    ChamadosController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarChamadoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_buscarPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_excluir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChamadosController_atualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarChamadoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_atualizarStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_atualizarResponsavel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarResponsavelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_adicionarComentario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarComentarioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
}
