/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_verificarSaude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AutenticacaoController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AutenticacaoController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsuariosController_buscarAtual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsuariosController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriasController_listar"];
        put?: never;
        post: operations["CategoriasController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chamados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChamadosController_listar"];
        put?: never;
        post: operations["ChamadosController_criar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chamados/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChamadosController_buscarPorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chamados/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ChamadosController_atualizarStatus"];
        trace?: never;
    };
    "/api/chamados/{id}/responsavel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ChamadosController_atualizarResponsavel"];
        trace?: never;
    };
    "/api/chamados/{id}/comentarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChamadosController_adicionarComentario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegistrarDto: {
            nome: string;
            email: string;
            senha: string;
        };
        /** @enum {string} */
        Papel: "USUARIO" | "AGENTE" | "ADMIN";
        UsuarioDto: {
            id: number;
            nome: string;
            email: string;
            papel: components["schemas"]["Papel"];
        };
        AuthRespostaDto: {
            token: string;
            usuario: components["schemas"]["UsuarioDto"];
        };
        LoginDto: {
            /** @example admin@local.dev */
            email: string;
            senha: string;
        };
        CategoriaDto: {
            id: number;
            nome: string;
        };
        CriarCategoriaDto: {
            nome: string;
        };
        /** @enum {string} */
        PrioridadeChamado: "BAIXA" | "MEDIA" | "ALTA";
        CriarChamadoDto: {
            titulo: string;
            descricao: string;
            prioridade?: components["schemas"]["PrioridadeChamado"];
            categoriaId?: number;
        };
        /** @enum {string} */
        StatusChamado: "ABERTO" | "EM_ANDAMENTO" | "RESOLVIDO" | "FECHADO";
        UsuarioResumoDto: {
            id: number;
            nome: string;
            email: string;
        };
        ComentarioDto: {
            id: number;
            mensagem: string;
            /** Format: date-time */
            criadoEm: string;
            autor: components["schemas"]["UsuarioResumoDto"];
        };
        ChamadoDto: {
            id: number;
            titulo: string;
            descricao: string;
            status: components["schemas"]["StatusChamado"];
            prioridade: components["schemas"]["PrioridadeChamado"];
            /** Format: date-time */
            criadoEm: string;
            /** Format: date-time */
            atualizadoEm: string;
            categoria: components["schemas"]["CategoriaDto"] | null;
            solicitante: components["schemas"]["UsuarioResumoDto"];
            responsavel: components["schemas"]["UsuarioResumoDto"] | null;
            comentarios?: components["schemas"]["ComentarioDto"][];
        };
        AtualizarStatusDto: {
            status: components["schemas"]["StatusChamado"];
        };
        AtualizarResponsavelDto: {
            responsavelId: number;
        };
        CriarComentarioDto: {
            mensagem: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_verificarSaude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AutenticacaoController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRespostaDto"];
                };
            };
        };
    };
    AutenticacaoController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRespostaDto"];
                };
            };
        };
    };
    UsuariosController_buscarAtual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    UsuariosController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"][];
                };
            };
        };
    };
    CategoriasController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"][];
                };
            };
        };
    };
    CategoriasController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarCategoriaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaDto"];
                };
            };
        };
    };
    ChamadosController_listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"][];
                };
            };
        };
    };
    ChamadosController_criar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarChamadoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_buscarPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_atualizarStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_atualizarResponsavel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarResponsavelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
    ChamadosController_adicionarComentario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarComentarioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChamadoDto"];
                };
            };
        };
    };
}
